### ISSUE TITLE
Cannot manually login

### ISSUE THREAD

**Issue by spatil181** [catalyst/moodle-auth_userkey#104]
Apart from SSO, if users want to login manually , they can't as the login page no longer works. Instead it says server url not found.
![image](https://github.com/catalyst/moodle-auth_userkey/assets/85994863/478fd04b-74da-4400-97b5-fe1177a3d0f1)
Any fix for this?

**Comment by dmitriim** [comment]
Hi @spatil181 

By design users using this auth method are not allowed to login manually using login form. See https://github.com/catalyst/moodle-auth_userkey/blob/MOODLE_33PLUS/auth.php#L131

However, the error you are referencing to doesn't look like directly related to the plugin. You may want to search a help through Moodle forums. To get help I'd suggest you to share as much information as you can. E.g. exact steps to replicate, URL examples and other useful information.

**Comment by dmitriim** [comment]
There is another issue similar to this one https://github.com/catalyst/moodle-auth_userkey/issues/98
